name: Dependabot auto-merge

on: pull_request_target

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: LeafLink/ci-tools/dependabot-auto-merge@main
        with:
          automation-pat: ${{ secrets.LEAFLINK_AUTOMATION_PAT }}
          update-type: patch
          merge-type: squash
