name: release

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next
      - next-major
      - '[0-9]+.x'

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v3

      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action@sha256:601fd6c1db9efbcfabd34ba4563e7d0b9eb0f8ba11316e3e7d6a9b6883dac8ba
        id: semantic
        with:
          tag_format: '${version}'
          branches: |
            [
              'main',
              'next',
              'next-major',
              '+([0-9])?(.{+([0-9]),x}).x',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.LEAFLINK_AUTOMATION_PAT }}

      - name: Deploy Latest Release to Dev
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          gh workflow run deploy -f environment=dev -f releaseVersion=${{ steps.semantic.outputs.release-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
