name: Stats Uploader

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  main:
    name: Upload Stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload Bundle Stats
        uses: actions/upload-artifact@v3
        with:
          name: bundle-size-stats
          path: stats.json
