# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: docker
    directory: /
    # Check for updates once a week
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      # Check for updates to GitHub Actions every Monday
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: daily
    # Disable rebasing for npm pull requests
    rebase-strategy: disabled
