repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.0
  hooks:
    - id: terraform_fmt
      args:
       - --args=-diff
    - id: terraform_tflint
      args:
      - --args=--config=.tflint.hcl
    - id: terraform_docs
